name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # Changed from read to write
  pages: write
  id-token: write
  deployments: write  # Added deployment permissions

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use GITHUB_TOKEN
        persist-credentials: true  # Persist credentials for subsequent steps
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Install dependencies
      run: |
        dotnet restore
        dotnet tool install -g Microsoft.Web.LibraryManager.Cli
        dotnet tool restore
    
    - name: Publish
      run: |
        dotnet publish -c Release -o release --nologo /p:BaseHref=/funciona/
        
        # Crear archivo 404.html para GitHub Pages
        cp release/wwwroot/index.html release/wwwroot/404.html
        
        # Crear .nojekyll para evitar el procesamiento de Jekyll
        touch release/wwwroot/.nojekyll
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: release/wwwroot
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
