name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [main]  # Cambia si usas otra rama
  workflow_dispatch:  # Permite ejecución manual

permissions:
  pages: write
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Usa tu versión de .NET

      - name: Install WASM tools
        run: dotnet workload install wasm-tools

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Blazor App
        run: |
          dotnet publish -c Release -o release \
            /p:BaseHref="/funciona/" \
            /p:StaticWebAssetBasePath="/funciona/" \
            /p:GHPages=true

      - name: Prepare for GitHub Pages
        run: |
          cd release/wwwroot
          # Asegurar que el base href sea correcto
          sed -i 's|<base href="/"|<base href="/funciona/"|g' index.html
          # Crear 404.html para SPA routing
          cp index.html 404.html
          # Prevenir procesamiento de Jekyll
          touch .nojekyll
          # Crear CORS para evitar problemas con recursos estáticos
          echo '/*   200' > _headers

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
